[programs.localnet]
passages = "2WHLLSwc7wsRen7w75Y6hUDeasf5Fjj1CPcuxzSXp9Qn"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/brianholt/.config/solana/id.json"

[scripts]
test = "npm run test:solana"
